name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/namadataset_preprocessing/train_student.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cek env
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas

      # Jalankan MLflow Project
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local

      # Setup Git LFS
      - name: Set up Git LFS
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main

      # Push hasil mlruns ke repo
      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
