name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/namadataset_preprocessing/train_student.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cek env
      - name: Check Env
        run: echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas

      # Jalankan MLflow Project
      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local

      # Ambil latest MLflow run_id
      - name: Get latest MLflow run_id
        run: |
          latest_run=$(ls -td mlruns/0/* | head -1 | xargs -n1 basename)
          echo "Latest run_id: $latest_run"
          echo "run_id=$latest_run" >> $GITHUB_ENV
